PRODUCTOS = [
    # Laptops
    {
        "nombre": "Laptop ASUS VivoBook 15 AMD Ryzen 5",
        "categoria": "Laptops",
        "precio": 749.99,
        "stock": 12,
        "stock_minimo": 5,
        "proveedor": "DistribuidoraTech Guayaquil",
        "ultima_actualizacion": "2026-05-01",
    },
    {
        "nombre": "Laptop HP Pavilion 15 Intel Core i5",
        "categoria": "Laptops",
        "precio": 699.99,
        "stock": 8,
        "stock_minimo": 5,
        "proveedor": "HP Ecuador S.A.",
        "ultima_actualizacion": "2026-05-01",
    },
    {
        "nombre": "Laptop Lenovo IdeaPad 3 Intel Core i3",
        "categoria": "Laptops",
        "precio": 549.99,
        "stock": 3,           # STOCK BAJO
        "stock_minimo": 5,
        "proveedor": "Lenovo Distribuidor Oficial Quito",
        "ultima_actualizacion": "2026-04-28",
    },
    {
        "nombre": "Laptop Dell Inspiron 15 Intel Core i7",
        "categoria": "Laptops",
        "precio": 1149.99,
        "stock": 2,           # STOCK BAJO
        "stock_minimo": 4,
        "proveedor": "Dell Ecuador",
        "ultima_actualizacion": "2026-04-25",
    },
    {
        "nombre": "MacBook Air M2 13 pulgadas 8GB RAM",
        "categoria": "Laptops",
        "precio": 1299.99,
        "stock": 5,
        "stock_minimo": 3,
        "proveedor": "iShop Ecuador",
        "ultima_actualizacion": "2026-05-02",
    },
    # Monitores
    {
        "nombre": "Monitor LG 27 pulgadas Full HD IPS",
        "categoria": "Monitores",
        "precio": 279.99,
        "stock": 6,
        "stock_minimo": 3,
        "proveedor": "LG Electronics Ecuador",
        "ultima_actualizacion": "2026-05-03",
    },
    {
        "nombre": "Monitor Samsung 24 pulgadas Curvo FHD",
        "categoria": "Monitores",
        "precio": 199.99,
        "stock": 9,
        "stock_minimo": 4,
        "proveedor": "Samsung Distribuidora Ecuador",
        "ultima_actualizacion": "2026-05-03",
    },
    {
        "nombre": "Monitor Philips 32 pulgadas 4K UHD",
        "categoria": "Monitores",
        "precio": 449.99,
        "stock": 3,
        "stock_minimo": 2,
        "proveedor": "DistribuidoraTech Guayaquil",
        "ultima_actualizacion": "2026-04-20",
    },
    # Periféricos
    {
        "nombre": "Teclado Mecánico Redragon K552 RGB",
        "categoria": "Periféricos",
        "precio": 79.99,
        "stock": 25,
        "stock_minimo": 10,
        "proveedor": "Gaming Imports Ecuador",
        "ultima_actualizacion": "2026-05-05",
    },
    {
        "nombre": "Mouse Logitech MX Master 3 Inalámbrico",
        "categoria": "Periféricos",
        "precio": 89.99,
        "stock": 15,
        "stock_minimo": 8,
        "proveedor": "Logitech Distribuidora Quito",
        "ultima_actualizacion": "2026-05-05",
    },
    {
        "nombre": "Mouse Inalámbrico Rapoo MT550 Multi-modo",
        "categoria": "Periféricos",
        "precio": 34.99,
        "stock": 4,           # STOCK BAJO
        "stock_minimo": 10,
        "proveedor": "Importadora Tecnológica S.A.",
        "ultima_actualizacion": "2026-04-22",
    },
    {
        "nombre": "Webcam Logitech C920 HD Pro 1080p",
        "categoria": "Periféricos",
        "precio": 89.99,
        "stock": 11,
        "stock_minimo": 5,
        "proveedor": "Logitech Distribuidora Quito",
        "ultima_actualizacion": "2026-05-04",
    },
    # Audio
    {
        "nombre": "Audífonos Sony WH-1000XM5 Noise Cancelling",
        "categoria": "Audio",
        "precio": 299.99,
        "stock": 5,
        "stock_minimo": 3,
        "proveedor": "Sony Ecuador",
        "ultima_actualizacion": "2026-05-01",
    },
    {
        "nombre": "Audífonos JBL Tune 510BT Inalámbricos",
        "categoria": "Audio",
        "precio": 59.99,
        "stock": 18,
        "stock_minimo": 6,
        "proveedor": "JBL Distribuidora Ecuador",
        "ultima_actualizacion": "2026-05-02",
    },
    {
        "nombre": "Micrófono Blue Yeti USB Condensador",
        "categoria": "Audio",
        "precio": 129.99,
        "stock": 4,
        "stock_minimo": 3,
        "proveedor": "Importadora Tecnológica S.A.",
        "ultima_actualizacion": "2026-04-30",
    },
    # Almacenamiento
    {
        "nombre": "Disco SSD Samsung 870 EVO 1TB SATA",
        "categoria": "Almacenamiento",
        "precio": 109.99,
        "stock": 20,
        "stock_minimo": 8,
        "proveedor": "Samsung Distribuidora Ecuador",
        "ultima_actualizacion": "2026-05-06",
    },
    {
        "nombre": "Disco SSD Kingston A400 500GB SATA",
        "categoria": "Almacenamiento",
        "precio": 54.99,
        "stock": 3,           # STOCK BAJO
        "stock_minimo": 8,
        "proveedor": "Kingston Distribuidora Quito",
        "ultima_actualizacion": "2026-04-20",
    },
    {
        "nombre": "Memoria USB SanDisk Ultra 64GB USB 3.0",
        "categoria": "Almacenamiento",
        "precio": 18.99,
        "stock": 50,
        "stock_minimo": 20,
        "proveedor": "SanDisk Ecuador",
        "ultima_actualizacion": "2026-05-07",
    },
    # Redes
    {
        "nombre": "Router TP-Link Archer AX73 WiFi 6 AX5400",
        "categoria": "Redes",
        "precio": 149.99,
        "stock": 7,
        "stock_minimo": 4,
        "proveedor": "TP-Link Ecuador",
        "ultima_actualizacion": "2026-05-03",
    },
    {
        "nombre": "Switch TP-Link TL-SG108 8 Puertos Gigabit",
        "categoria": "Redes",
        "precio": 39.99,
        "stock": 12,
        "stock_minimo": 5,
        "proveedor": "TP-Link Ecuador",
        "ultima_actualizacion": "2026-05-03",
    },
    # Accesorios
    {
        "nombre": "Cable HDMI 2.0 Belden 2 metros 4K",
        "categoria": "Accesorios",
        "precio": 14.99,
        "stock": 35,
        "stock_minimo": 15,
        "proveedor": "Cables & Conectores Quito",
        "ultima_actualizacion": "2026-05-08",
    },
    {
        "nombre": "Cargador USB-C 65W Anker PowerPort",
        "categoria": "Accesorios",
        "precio": 39.99,
        "stock": 2,           # STOCK BAJO
        "stock_minimo": 8,
        "proveedor": "Anker Distribuidora Ecuador",
        "ultima_actualizacion": "2026-04-18",
    },
    {
        "nombre": "Hub USB-C 7 en 1 Anker PowerExpand",
        "categoria": "Accesorios",
        "precio": 49.99,
        "stock": 14,
        "stock_minimo": 6,
        "proveedor": "Anker Distribuidora Ecuador",
        "ultima_actualizacion": "2026-05-02",
    },
]


CLIENTES = [
    {
        "nombre": "María Fernanda López",
        "email": "mflopez@constructoraandina.ec",
        "telefono": "0991234567",
        "empresa": "Constructora Andina S.A.",
        "ciudad": "Quito",
        "fecha_registro": "2025-06-10",
    },
    {
        "nombre": "Carlos Oswaldo Mendoza",
        "email": "cmendoza@quitoimperial.ec",
        "telefono": "0987654321",
        "empresa": "Hotel Quito Imperial",
        "ciudad": "Quito",
        "fecha_registro": "2025-07-22",
    },
    {
        "nombre": "Andrea Paola Salazar",
        "email": "asalazar@edutechec.com",
        "telefono": "0998765432",
        "empresa": "EduTech Ecuador",
        "ciudad": "Quito",
        "fecha_registro": "2025-08-15",
    },
    {
        "nombre": "Roberto Eduardo Espinoza",
        "email": "respinoza@espinozalaw.ec",
        "telefono": "0994567890",
        "empresa": "Estudio Jurídico Espinoza",
        "ciudad": "Guayaquil",
        "fecha_registro": "2025-05-03",
    },
    {
        "nombre": "Gabriela Cristina Mora",
        "email": "gmora@corporacionmora.ec",
        "telefono": "0992345678",
        "empresa": "Corporación Mora & Asociados",
        "ciudad": "Cuenca",
        "fecha_registro": "2025-09-20",
    },
    {
        "nombre": "Diego Alejandro Herrera",
        "email": "dherrera@techsolec.ec",
        "telefono": "0993456789",
        "empresa": "TechSol Ecuador Cía. Ltda.",
        "ciudad": "Quito",
        "fecha_registro": "2025-10-05",
    },
    {
        "nombre": "Valentina Isabel Castillo",
        "email": "vcastillo@mediaquito.ec",
        "telefono": "0995678901",
        "empresa": "MediaQuito Producciones",
        "ciudad": "Quito",
        "fecha_registro": "2025-11-12",
    },
    {
        "nombre": "Andrés Felipe Palacios",
        "email": "apalacios@palaciosarq.ec",
        "telefono": "0996789012",
        "empresa": "Palacios Arquitectos & Diseño",
        "ciudad": "Quito",
        "fecha_registro": "2025-04-18",
    },
    {
        "nombre": "Lorena Patricia Vásquez",
        "email": "lvasquez@clinicavidasana.ec",
        "telefono": "0997890123",
        "empresa": "Clínica Vida Sana",
        "ciudad": "Ambato",
        "fecha_registro": "2025-12-01",
    },
    {
        "nombre": "Miguel Ángel Torres",
        "email": "matorres@distribuidoraec.ec",
        "telefono": "0990123456",
        "empresa": "Distribuidora Torres Hermanos",
        "ciudad": "Guayaquil",
        "fecha_registro": "2025-03-14",
    },
    {
        "nombre": "Patricia Eugenia Guerrero",
        "email": "pguerrero@colegiosf.ec",
        "telefono": "0982345678",
        "empresa": "Colegio San Francisco de Asís",
        "ciudad": "Loja",
        "fecha_registro": "2025-07-08",
    },
    {
        "nombre": "Sebastián Alejandro Ordóñez",
        "email": "sordonez@startupec.io",
        "telefono": "0983456789",
        "empresa": "StartupEC Innovación",
        "ciudad": "Quito",
        "fecha_registro": "2026-01-20",
    },
    {
        "nombre": "Carmen Elena Alvarado",
        "email": "calvarado@hotelinn.ec",
        "telefono": "0984567890",
        "empresa": "Hotel Manta Inn & Suites",
        "ciudad": "Manta",
        "fecha_registro": "2025-08-30",
    },
    {
        "nombre": "Fernando José Rivadeneira",
        "email": "frivadeneira@rivadeneiraecia.ec",
        "telefono": "0985678901",
        "empresa": "Rivadeneira & Cía. S.A.",
        "ciudad": "Ibarra",
        "fecha_registro": "2025-06-25",
    },
    {
        "nombre": "Natalia Gabriela Benítez",
        "email": "nbenitez@softwareec.ec",
        "telefono": "0986789012",
        "empresa": "SoftwareEC Soluciones",
        "ciudad": "Guayaquil",
        "fecha_registro": "2026-02-14",
    },
]



VENTAS = [
    # Marzo 2026
    {"cliente_id": 1, "producto_id": 1,  "cantidad": 2,  "precio_unitario": 749.99,  "total": 1499.98, "fecha": "2026-03-02", "estado": "completada"},
    {"cliente_id": 3, "producto_id": 9,  "cantidad": 5,  "precio_unitario": 79.99,   "total": 399.95,  "fecha": "2026-03-05", "estado": "completada"},
    {"cliente_id": 6, "producto_id": 16, "cantidad": 10, "precio_unitario": 109.99,  "total": 1099.90, "fecha": "2026-03-08", "estado": "completada"},
    {"cliente_id": 10,"producto_id": 19, "cantidad": 1,  "precio_unitario": 149.99,  "total": 149.99,  "fecha": "2026-03-10", "estado": "completada"},
    {"cliente_id": 2, "producto_id": 6,  "cantidad": 3,  "precio_unitario": 279.99,  "total": 839.97,  "fecha": "2026-03-12", "estado": "completada"},
    {"cliente_id": 8, "producto_id": 1,  "cantidad": 1,  "precio_unitario": 749.99,  "total": 749.99,  "fecha": "2026-03-15", "estado": "completada"},
    {"cliente_id": 5, "producto_id": 13, "cantidad": 2,  "precio_unitario": 299.99,  "total": 599.98,  "fecha": "2026-03-17", "estado": "completada"},
    {"cliente_id": 11,"producto_id": 3,  "cantidad": 10, "precio_unitario": 549.99,  "total": 5499.90, "fecha": "2026-03-18", "estado": "completada"},
    {"cliente_id": 4, "producto_id": 10, "cantidad": 3,  "precio_unitario": 89.99,   "total": 269.97,  "fecha": "2026-03-20", "estado": "completada"},
    {"cliente_id": 12,"producto_id": 12, "cantidad": 1,  "precio_unitario": 89.99,   "total": 89.99,   "fecha": "2026-03-22", "estado": "completada"},
    {"cliente_id": 15,"producto_id": 2,  "cantidad": 2,  "precio_unitario": 699.99,  "total": 1399.98, "fecha": "2026-03-25", "estado": "completada"},
    {"cliente_id": 7, "producto_id": 14, "cantidad": 4,  "precio_unitario": 59.99,   "total": 239.96,  "fecha": "2026-03-27", "estado": "completada"},
    {"cliente_id": 9, "producto_id": 18, "cantidad": 20, "precio_unitario": 18.99,   "total": 379.80,  "fecha": "2026-03-28", "estado": "completada"},
    {"cliente_id": 1, "producto_id": 6,  "cantidad": 2,  "precio_unitario": 279.99,  "total": 559.98,  "fecha": "2026-03-30", "estado": "completada"},
    # Abril 2026
    {"cliente_id": 3, "producto_id": 5,  "cantidad": 1,  "precio_unitario": 1299.99, "total": 1299.99, "fecha": "2026-04-02", "estado": "completada"},
    {"cliente_id": 6, "producto_id": 9,  "cantidad": 8,  "precio_unitario": 79.99,   "total": 639.92,  "fecha": "2026-04-03", "estado": "completada"},
    {"cliente_id": 14,"producto_id": 19, "cantidad": 2,  "precio_unitario": 149.99,  "total": 299.98,  "fecha": "2026-04-05", "estado": "completada"},
    {"cliente_id": 10,"producto_id": 7,  "cantidad": 5,  "precio_unitario": 199.99,  "total": 999.95,  "fecha": "2026-04-07", "estado": "completada"},
    {"cliente_id": 8, "producto_id": 16, "cantidad": 4,  "precio_unitario": 109.99,  "total": 439.96,  "fecha": "2026-04-09", "estado": "completada"},
    {"cliente_id": 2, "producto_id": 1,  "cantidad": 5,  "precio_unitario": 749.99,  "total": 3749.95, "fecha": "2026-04-10", "estado": "completada"},
    {"cliente_id": 5, "producto_id": 10, "cantidad": 2,  "precio_unitario": 89.99,   "total": 179.98,  "fecha": "2026-04-12", "estado": "completada"},
    {"cliente_id": 13,"producto_id": 20, "cantidad": 3,  "precio_unitario": 39.99,   "total": 119.97,  "fecha": "2026-04-14", "estado": "completada"},
    {"cliente_id": 1, "producto_id": 4,  "cantidad": 1,  "precio_unitario": 1149.99, "total": 1149.99, "fecha": "2026-04-15", "estado": "pendiente"},
    {"cliente_id": 11,"producto_id": 2,  "cantidad": 5,  "precio_unitario": 699.99,  "total": 3499.95, "fecha": "2026-04-17", "estado": "completada"},
    {"cliente_id": 4, "producto_id": 13, "cantidad": 1,  "precio_unitario": 299.99,  "total": 299.99,  "fecha": "2026-04-18", "estado": "completada"},
    {"cliente_id": 7, "producto_id": 15, "cantidad": 2,  "precio_unitario": 129.99,  "total": 259.98,  "fecha": "2026-04-20", "estado": "completada"},
    {"cliente_id": 12,"producto_id": 23, "cantidad": 3,  "precio_unitario": 49.99,   "total": 149.97,  "fecha": "2026-04-22", "estado": "completada"},
    {"cliente_id": 9, "producto_id": 12, "cantidad": 2,  "precio_unitario": 89.99,   "total": 179.98,  "fecha": "2026-04-23", "estado": "cancelada"},
    {"cliente_id": 15,"producto_id": 8,  "cantidad": 2,  "precio_unitario": 449.99,  "total": 899.98,  "fecha": "2026-04-25", "estado": "completada"},
    {"cliente_id": 6, "producto_id": 17, "cantidad": 3,  "precio_unitario": 54.99,   "total": 164.97,  "fecha": "2026-04-27", "estado": "completada"},
    {"cliente_id": 3, "producto_id": 22, "cantidad": 1,  "precio_unitario": 39.99,   "total": 39.99,   "fecha": "2026-04-28", "estado": "completada"},
    {"cliente_id": 14,"producto_id": 10, "cantidad": 4,  "precio_unitario": 89.99,   "total": 359.96,  "fecha": "2026-04-29", "estado": "pendiente"},
    {"cliente_id": 8, "producto_id": 14, "cantidad": 6,  "precio_unitario": 59.99,   "total": 359.94,  "fecha": "2026-04-30", "estado": "completada"},
    # Mayo 2026
    {"cliente_id": 1, "producto_id": 9,  "cantidad": 3,  "precio_unitario": 79.99,   "total": 239.97,  "fecha": "2026-05-02", "estado": "completada"},
    {"cliente_id": 5, "producto_id": 6,  "cantidad": 4,  "precio_unitario": 279.99,  "total": 1119.96, "fecha": "2026-05-03", "estado": "completada"},
    {"cliente_id": 10,"producto_id": 1,  "cantidad": 3,  "precio_unitario": 749.99,  "total": 2249.97, "fecha": "2026-05-04", "estado": "completada"},
    {"cliente_id": 2, "producto_id": 23, "cantidad": 5,  "precio_unitario": 49.99,   "total": 249.95,  "fecha": "2026-05-05", "estado": "completada"},
    {"cliente_id": 7, "producto_id": 2,  "cantidad": 2,  "precio_unitario": 699.99,  "total": 1399.98, "fecha": "2026-05-06", "estado": "pendiente"},
    {"cliente_id": 12,"producto_id": 18, "cantidad": 5,  "precio_unitario": 18.99,   "total": 94.95,   "fecha": "2026-05-07", "estado": "completada"},
    {"cliente_id": 4, "producto_id": 7,  "cantidad": 2,  "precio_unitario": 199.99,  "total": 399.98,  "fecha": "2026-05-08", "estado": "completada"},
    {"cliente_id": 15,"producto_id": 16, "cantidad": 2,  "precio_unitario": 109.99,  "total": 219.98,  "fecha": "2026-05-08", "estado": "completada"},
    {"cliente_id": 6, "producto_id": 5,  "cantidad": 1,  "precio_unitario": 1299.99, "total": 1299.99, "fecha": "2026-05-09", "estado": "pendiente"},
    {"cliente_id": 9, "producto_id": 15, "cantidad": 1,  "precio_unitario": 129.99,  "total": 129.99,  "fecha": "2026-05-09", "estado": "completada"},
]



LEADS = [
    # Seguimiento semana 12-16 mayo 2026
    {
        "nombre_contacto": "Carlos Mendoza Villacís",
        "empresa": "Hotel Quito Imperial",
        "email": "carlos@quitoimperial.ec",
        "telefono": "0987654321",
        "interes": "Renovación de equipos de cómputo para 15 habitaciones: laptops, monitores y teclados",
        "valor_estimado": 12500.00,
        "estado": "en_negociacion",
        "fecha_creacion": "2026-04-01",
        "fecha_seguimiento": "2026-05-12",
        "notas": "Interesado en financiamiento a 12 meses. Reunión con gerente de operaciones el lunes.",
    },
    {
        "nombre_contacto": "Prof. Marcelo Quispe",
        "empresa": "Colegio Nuevo Mundo",
        "email": "mquispe@colegionu.ec",
        "telefono": "0998123456",
        "interes": "Implementación de laboratorio de computación: 20 computadores y proyector",
        "valor_estimado": 15000.00,
        "estado": "contactado",
        "fecha_creacion": "2026-04-12",
        "fecha_seguimiento": "2026-05-13",
        "notas": "Requiere factura institucional. Proceso de compra pública. Confirmar RUC.",
    },
    {
        "nombre_contacto": "Ing. Rosa Andrade",
        "empresa": "Telecom Andina S.A.",
        "email": "randrade@telecomandina.ec",
        "telefono": "0993214567",
        "interes": "Renovación de infraestructura de red: switches, routers y cableado para 3 pisos",
        "valor_estimado": 8500.00,
        "estado": "en_negociacion",
        "fecha_creacion": "2026-04-08",
        "fecha_seguimiento": "2026-05-14",
        "notas": "Tienen presupuesto aprobado. Esperan cotización formal con desglose por piso.",
    },
    {
        "nombre_contacto": "Dra. Pamela Ramos",
        "empresa": "Clínica Metropolitana Quito",
        "email": "pramos@clinicametro.ec",
        "telefono": "0994321987",
        "interes": "Equipos de cómputo para área de enfermería y recepción: laptops y tablets",
        "valor_estimado": 6200.00,
        "estado": "nuevo",
        "fecha_creacion": "2026-04-20",
        "fecha_seguimiento": "2026-05-15",
        "notas": "Contacto por referido de Constructora Andina. Primera llamada fue positiva.",
    },
    {
        "nombre_contacto": "Lic. Vanessa Loor",
        "empresa": "StartupHub Guayaquil",
        "email": "vloor@startuphub.ec",
        "telefono": "0985432109",
        "interes": "Equipamiento completo para espacio de coworking: 15 laptops, monitores y accesorios",
        "valor_estimado": 18500.00,
        "estado": "en_negociacion",
        "fecha_creacion": "2026-04-15",
        "fecha_seguimiento": "2026-05-16",
        "notas": "Inversión grande. Quieren demo de productos antes de decidir. Visita agendada.",
    },
    # Seguimiento posterior
    {
        "nombre_contacto": "Sra. Karina Pacheco",
        "empresa": "Farmacia Económica Nacional",
        "email": "kpacheco@farmaciaecon.ec",
        "telefono": "0987890123",
        "interes": "Sistema de cajas registradoras y escáneres para 8 sucursales",
        "valor_estimado": 3800.00,
        "estado": "contactado",
        "fecha_creacion": "2026-04-30",
        "fecha_seguimiento": "2026-05-19",
        "notas": "Tienen sistema POS propio, solo necesitan hardware compatible.",
    },
    {
        "nombre_contacto": "Arq. Luis Benalcázar",
        "empresa": "Municipio de Ambato",
        "email": "lbenalcazar@municipioambato.gob.ec",
        "telefono": "0996541230",
        "interes": "Computadores y periféricos para 8 departamentos municipales",
        "valor_estimado": 28000.00,
        "estado": "contactado",
        "fecha_creacion": "2026-03-25",
        "fecha_seguimiento": "2026-05-20",
        "notas": "Proceso de contratación pública. Plazo estimado de adjudicación: 60 días.",
    },
    {
        "nombre_contacto": "Sr. Rodrigo Cevallos",
        "empresa": "Banco Andino del Ecuador",
        "email": "rcevallos@bancandino.ec",
        "telefono": "0992109876",
        "interes": "Periféricos y equipos de seguridad para 50 puntos de atención a nivel nacional",
        "valor_estimado": 22000.00,
        "estado": "en_negociacion",
        "fecha_creacion": "2026-04-22",
        "fecha_seguimiento": "2026-05-22",
        "notas": "Necesitan aprobación de gerencia de IT. Proceso interno lento pero seguro.",
    },
    {
        "nombre_contacto": "Msc. Adriana Naranjo",
        "empresa": "Universidad Técnica del Norte",
        "email": "anaranjo@utn.edu.ec",
        "telefono": "0993210987",
        "interes": "Servidores, switches y laboratorio de redes para facultad de sistemas",
        "valor_estimado": 45000.00,
        "estado": "contactado",
        "fecha_creacion": "2026-04-25",
        "fecha_seguimiento": "2026-05-28",
        "notas": "Proyecto grande. Requiere visita técnica al campus en Ibarra.",
    },
    # Sin fecha de seguimiento
    {
        "nombre_contacto": "Ing. Marco Rivera",
        "empresa": "Constructora Rivera & Hijos",
        "email": "mrivera@riveraconstruye.ec",
        "telefono": "0997654321",
        "interes": "Laptops de ingeniería para equipo técnico de campo: 5 personas",
        "valor_estimado": 9800.00,
        "estado": "cerrado_ganado",
        "fecha_creacion": "2026-03-10",
        "fecha_seguimiento": None,
        "notas": "Pedido realizado. Entrega completada el 18 de abril. Cliente muy satisfecho.",
    },
    {
        "nombre_contacto": "Sra. Fanny Intriago",
        "empresa": "Hotel La Selva Amazónica",
        "email": "fintriago@laselvahotel.ec",
        "telefono": "0981234567",
        "interes": "Sistema WiFi y tablets para 30 habitaciones de ecoturismo",
        "valor_estimado": 3200.00,
        "estado": "cerrado_perdido",
        "fecha_creacion": "2026-03-05",
        "fecha_seguimiento": None,
        "notas": "Eligieron otro proveedor por precio más bajo. Mantener contacto para renovación 2027.",
    },
    {
        "nombre_contacto": "Lic. Pablo Zurita",
        "empresa": "Agencia Creativa Pixel",
        "email": "pzurita@pixelagencia.ec",
        "telefono": "0984321098",
        "interes": "MacBooks y monitores 4K para equipo de diseño gráfico de 4 personas",
        "valor_estimado": 7500.00,
        "estado": "nuevo",
        "fecha_creacion": "2026-05-05",
        "fecha_seguimiento": None,
        "notas": "Llegó por referencia de Instagram. Enviar catálogo de productos Apple y Philips.",
    },
    {
        "nombre_contacto": "Ing. Jaime Aucancela",
        "empresa": "TransAndina Logística",
        "email": "jaucancela@transandina.ec",
        "telefono": "0986543210",
        "interes": "Tablets robustas y handhelds para gestión de inventario en bodega",
        "valor_estimado": 5600.00,
        "estado": "nuevo",
        "fecha_creacion": "2026-05-07",
        "fecha_seguimiento": "2026-06-01",
        "notas": "Necesitan dispositivos resistentes a polvo y golpes. Preguntar por modelos IP65.",
    },
]
